src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
class Formation
{
    // Début de chemin vers les images
    private const CHEMIN_IMAGE = "https://i.ytimg.com/vi/";
        
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $publishedAt = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $videoId = null;

    #[ORM\ManyToOne(inversedBy: 'formations')]
    private ?Playlist $playlist = null;

    /**
     * @var Collection<int, Categorie>
     */
    #[ORM\ManyToMany(targetEntity: Categorie::class, inversedBy: 'formations')]
    private Collection $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    // Getter pour l'ID
    public function getId(): ?int
    {
        return $this->id;
    }

    // Getter pour la date de publication
    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    // Setter pour la date de publication
    public function setPublishedAt(?\DateTimeInterface $publishedAt): static
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    // Méthode pour obtenir la date de publication sous forme de chaîne
    public function getPublishedAtString(): string {
        if($this->publishedAt == null){
            return "";
        }
        return $this->publishedAt->format('d/m/Y');     
    }      
    
    // Getter pour le titre
    public function getTitle(): ?string
    {
        return $this->title;
    }

    // Setter pour le titre
    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    // Getter pour la description
    public function getDescription(): ?string
    {
        return $this->description;
    }

    // Setter pour la description
    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    // Getter pour l'ID de la vidéo
    public function getVideoId(): ?string
    {
        return $this->videoId;
    }

    // Setter pour l'ID de la vidéo
    public function setVideoId(?string $videoId): static
    {
        $this->videoId = $videoId;

        return $this;
    }

    // Méthode pour obtenir la miniature de la vidéo
    public function getMiniature(): ?string
    {
        return self::CHEMIN_IMAGE.$this->videoId."/default.jpg";
    }

    // Méthode pour obtenir l'image de la vidéo
    public function getPicture(): ?string
    {
        return self::CHEMIN_IMAGE.$this->videoId."/hqdefault.jpg";
    }
    
    // Getter pour la playlist
    public function getPlaylist(): ?playlist
    {
        return $this->playlist;
    }

    // Setter pour la playlist
    public function setPlaylist(?Playlist $playlist): static
    {
        $this->playlist = $playlist;

        return $this;
    }

    /**
     * @return Collection<int, Categorie>
     */
    // Getter pour les catégories
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    // Méthode pour ajouter une catégorie
    public function addCategory(Categorie $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    // Méthode pour supprimer une catégorie
    public function removeCategory(Categorie $category): static
    {
        $this->categories->removeElement($category);

        return $this;
    }
}

templates/pages/accueil.html.twig
{% extends "basefront.html.twig" %}

{% block body %}
    <p class="mt-3">
        <h3>Bienvenue sur le site de MediaTek86 consacré aux formations en ligne</h3>
    </p>
    <p class="mt-3">
        Vous allez pouvoir vous former à différents outils numériques gratuitement et directement en ligne.<br />
        Dans la partie <strong><a href="{{ path('formations') }}" class="link-info">Formations</a></strong>, vous trouverez la liste des formations proposées.
        Vous pourrez faire des recherches et des tris. 
        En cliquant sur la capture, vous accèderez à la présentation plus détaillée de la formation ainsi que la vidéo correspondante.<BR />
        Vous pouvez aussi retrouver les vidéos regroupées dans des playlists, dans la partie <strong><a href="{{ path('playlists') }}" class="link-info">Playlists</a></strong>.
    </p>
    <p>
        Voici les <strong>deux dernières formations</strong> ajoutées au catalogue :
        <table class="table" description="Table des deux dernières formations ajoutées avec photo et lien">
            <thead>
                <tr>
                    <th>Photo</th>
                    <th>Détails de la formation</th>
                </tr>
            </thead>
            <tbody>
                {% for formation in formations %}
                    <tr>
                        <td>
                            {% if formation.picture %}
                                <a href="{{ path('formations.showone', {id:formation.id}) }}">
                                    <img src="{{ formation.picture | default('default_image.jpg') }}" class="card-img-top" style="width:100%;height:auto;" alt="Image de la formation {{ formation.title | default('Formation sans nom') }}">
                                </a>
                            {% endif %}
                        </td>
                        <td>
                            <div class="col">
                                <p>{{ formation.publishedatstring }}</p>
                                <h5 class="text-info mt-1">
                                    {{ formation.title }}
                                </h5>
                                {% if formation.playlist is not null %}
                                <strong>playlist : </strong>{{ formation.playlist.name }}<br />
                                {% else %}
                                <strong>playlist : </strong>aucune<br />
                                {% endif %}
                                <strong>catégories : </strong> 
                                {% for categorie in formation.categories %}
                                    {{ categorie.name }}&nbsp;
                                {% endfor %}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>        
    </p>
{% endblock %}

templates/pages/baseadminpage.html.twig
{% extends "base.html.twig" %}
{% block title %}{% endblock %}
{% block stylesheets %}{% endblock %}
{% block top %}
    <div class="container">
        <!-- Déconnexion -->
        <div class="text-end">
            <a href="{{ path('logout') }}" class="link-dark">Se déconnecter</a>
        </div>
        <!-- Bannière et Titre -->
        <div class="row align-items-center">
            <div class="col-md-6">
                <img src="{{ app.request.getBasePath()~'/banniere.jpg' }}" alt="Bannière" class="img-fluid">
            </div>
            <div class="col-md-6 text-end">
                <h2 style="font-size: 24px; font-weight: bold; color: red;">🛠️ Back office 🛠️</h2>
            </div>
        </div>
        <!-- Menu -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light mt-4">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('admin.formations') }}">Formations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('admin.playlists') }}">Playlists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('admin.categories') }}">Catégories</a>
                    </li>
                </ul>
                <a class="btn btn-outline-dark" href="{{ path('accueil') }}">🚪 Retour à l'accueil</a>
            </div>
        </nav>
    </div>
{% endblock %}
{% block body %}
{% endblock %}
{% block footer %}
    <footer class="container text-center mt-4">
        <hr>
        <p>
            <small>
                Consultez nos 
                <a href="{{ path('cgu') }}" class="link-secondary">Conditions Générales d'Utilisation</a>
            </small>
        </p>
    </footer>
{% endblock %}
{% block javascripts %}{% endblock %}

templates/pages/categories.html.twig
{% extends "basefront.html.twig" %}
{% block title %}Categories
{% endblock %}
{% block body %}
	<div class="row mt-3">
		<div class="col">
			<h2>
				gestion des categories
			</h2>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>nom</th>
						<th>nombre de formations</th>
						<th>actions</th>
					</tr>
				</thead>
				<tbody>
					{% for categorie in categories %}
						<tr>
							<td>{{ categorie.name }}</td>
							<td>{{ categorie.formations|length }}</td>
							<td></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

{% endblock %}

templates/pages/formations.html.twig
{% extends "basefront.html.twig" %}
{% block body %}
	<table class="table table-striped">
		<caption>Tableau de formation</caption>
		<thead>
			<tr>
				<th class="text-left align-top" scope="col">
					Formation<br/>
					<a href="{{ path('formations.sort', {champ:'title', ordre:'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">Croissant</a>
					<a href="{{ path('formations.sort', {champ:'title', ordre:'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">Décroissant</a>
					<form class="form-inline mt-1" method="POST" action="{{ path('formations.findAllContain', {champ:'title'}) }}">
						<div class="form-group mr-1 mb-2">
							<input type="text" class="sm" name="recherche" value="{% if valeur|default and not table|default %}{{ valeur }}{% endif %}">
							<input type="hidden" name="_token" value="{{ csrf_token('filtre_title') }}">
							<button type="submit" class="btn btn-info mb-2 btn-sm">filtrer</button>
						</div>
					</form>
				</th>
				<th class="text-left align-top" scope="col">
					Playlist<br/>
					<a href="{{ path('formations.sort', {table:'playlist', champ:'name', ordre:'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">Croissant</a>
					<a href="{{ path('formations.sort', {table:'playlist', champ:'name', ordre:'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">Décroissant</a>
					<form class="form-inline mt-1" method="POST" action="{{ path('formations.findAllContain', {champ:'name', table:'playlist'}) }}">
						<div class="form-group mr-1 mb-2">
							<input type="text" class="sm" name="recherche" value="{% if valeur|default and table|default and table=='playlist' %}{{ valeur }}{% endif %}">
							<input type="hidden" name="_token" value="{{ csrf_token('filtre_name') }}">
							<button type="submit" class="btn btn-info mb-2 btn-sm">filtrer</button>
						</div>
					</form>
				</th>
				<th class="text-left align-top" scope="col">
					Catégories
					<form class="form-inline mt-1" method="POST" action="{{ path('formations.findAllContain', {champ:'id', table:'categories'}) }}">
						<select class="form-select form-select-sm" name="recherche" id="recherche" onchange="this.form.submit()">
							<option value=""></option>
							{% for categorie in categories %}
								<option {% if valeur|default and valeur==categorie.id %} selected {% endif %} value="{{ categorie.id }}">
									{{ categorie.name }}
								</option>
							{% endfor %}
						</select>
					</form>
				</th>
				<th class="text-center align-top" scope="col">
					Date<br/>
					<a href="{{ path('formations.sort', {champ:'publishedAt', ordre:'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">Ancien</a>
					<a href="{{ path('formations.sort', {champ:'publishedAt', ordre:'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">Récent</a>
				</th>
			</tr>
		</thead>
		<tbody>
			{% for formation in formations %}
				<tr class="align-middle">
					<td>
						<h5 class="text-info">
							{{ formation.title }}
						</h5>
					</td>
					<td class="text-left">
						{% if formation.playlist %}
							{{ formation.playlist.name }}
						{% endif %}
					</td>
					<td class="text-left">
						{% for categorie in formation.categories %}
							{{ categorie.name }}<br/>
						{% endfor %}
					</td>
					<td class="text-center">
						{{ formation.publishedatstring }}
					</td>
					<td class="text-center">
						{% if formation.miniature %}
							<a href="{{ path('formations.showone', {id: formation.id}) }}">
								<img src="{{ formation.miniature }}" alt="image miniature" class="img-thumbnail" style="max-width: 100px;">
							</a>
						{% endif %}
					</td>
					<!-- Bouton Modifier (utilise la route avec "formations" au pluriel) -->
					{% if app.request.get('_route') starts with 'admin' %}
						<td class="text-center">
							<a href="{{ path('formations.edit', {id: formation.id}) }}" class="btn btn-primary btn-sm">Modifier</a>
						</td>
					{% endif %}
				</tr>
			{% else %}
				<tr>
					<td colspan="7" class="text-center">Aucune formation disponible</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/pages/playlists.html.twig
{% extends "basefront.html.twig" %}
{% block body %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="text-left align-top" scope="col">
                    playlist<br />
                    <a href="{{ path('playlists.sort', {champ:'name', ordre:'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true"><</a>
                    <a href="{{ path('playlists.sort', {champ:'name', ordre:'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">></a>
                    <form class="form-inline mt-1" method="POST" action="{{ path('playlists.findallcontain', {champ:'name'}) }}">
                        <div class="form-group mr-1 mb-2">
                            <input type="text" class="sm" name="recherche" 
                                   value="{% if valeur|default and not table|default %}{{ valeur }}{% endif %}">
                            <input type="hidden" name="_token" value="{{ csrf_token('filtre_name') }}">
                            <button type="submit" class="btn btn-info mb-2 btn-sm">filtrer</button>
                        </div>
                    </form>                    
                </th>
                <th class="text-left align-top" scope="col">
                    catégories
                    
                    <form class="form-inline mt-1" method="POST" action="{{ path('playlists.findallcontain', {champ:'id', table:'categories'}) }}">
                        <select class="form-select form-select-sm" name="recherche" id="recherche" onchange="this.form.submit()">
                            <option value=""></option>
                            {% for categorie in categories %}
                                <option 
                                    {% if valeur|default and valeur==categorie.id %} 
                                        selected
                                    {% endif %} 
                                    value="{{ categorie.id }}">{{ categorie.name }}
                                </option>
                            {% endfor %}
                        </select>                    
                    </form>            
                </th>
                <th class="text-center align-top" scope="col">
                    <a href="{{ path('playlists.sort', {champ: 'formationCount', ordre: 'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">📈</a>
                    Nombre de formations
                    <a href="{{ path('playlists.sort', {champ: 'formationCount', ordre: 'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">📉</a>
                </th>
                <th class="text-center align-top" scope="col">
                    &nbsp;
                </th>				
            </tr>
        </thead>
        <tbody>
            <!-- boucle sur les playlists -->
            {% if playlists|length > 0 %}
                {% for k in 0..playlists|length-1 %}
                    <tr class="align-middle">
                        <td>
                            <h5 class="text-info">
                                {{ playlists[k].name }}
                            </h5>
                        </td>                 
                        <td class="text-left">
                            {% set categories = playlists[k].categoriesplaylist %}
                            {% if categories|length > 0  %}
                                {% for c in 0..categories|length-1 %}
                                    &nbsp;{{ categories[c] }}                                  
                                {% endfor %}
                            {% endif %}
                        </td>   
                        <!-- Affichage du nombre de formations -->
                        <td class="text-center">
                            {{ playlists[k].formations|length }} <!-- Nombre de formations -->
                        </td>                                            
                        <td class="text-center">
                            <a href="{{ path('playlists.showone', {id:playlists[k].id}) }}" class="btn btn-secondary">Voir détail</a>
                        </td> 					
                    </tr>
                {% endfor %}	
            {% endif %}
        </tbody>
    </table>
{% endblock %}